#!/bin/sh
# prerm script for ArPiRobot-DeployTool
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove|upgrade|deconfigure)
        echo "Removing pycache"
        find src -type d -name __pycache__ -exec rm -r {} \; > /dev/null 2>&1

        echo "Removing desktop menu entry"
        xdg-desktop-menu uninstall ArPiRobot-DeployTool.desktop > /dev/null 2>&1
        rm ArPiRobot-DeployTool.desktop
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

